# Generated by Django 5.1.6 on 2025-03-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('temperature', models.FloatField()),
                ('respiration_rate', models.PositiveIntegerField()),
                ('service', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=255)),
                ('medicine', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
